name: Deploy SSL certificate to Bunny CDN
description: Deploy SSL certificate to Bunny CDN.
branding:
  icon: lock
  color: blue
inputs:
  id:
    description: The ID of the requested Pull Zone
    required: true
  hostname:
    description: The hostname to which the hostname will be added
    required: true
  access-key:
    description: The API access key from https://dash.bunny.net/account/settings
    required: true
  fullchain-file:
    description: The file path of the PEM fullchain certificate.
    required: true
  key-file:
    description: The file path of the PEM private key file.
    required: true
runs:
  using: node16
  main: bootstrap.js
